# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_s3}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Dell", "Roland Venesz"]
  s.date = %q{2013-05-14}
  s.description = %q{Plugin to have Redmine store uploads on S3}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = ["README.rdoc"]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "config/s3.yml.example",
    "lib/redmine_s3.rb",
    "lib/redmine_s3/railtie.rb",
    "lib/redmine_s3/attachment_patch.rb",
    "lib/redmine_s3/attachments_controller_patch.rb",
    "test/test_helper.rb" ]
  s.homepage = %q{http://github.com/steerio/redmine_s3}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{TODO}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Plugin to have Redmine store uploads on S3}
  s.test_files = [
    "test/test_helper.rb"
  ]

  s.add_dependency 'aws-sdk', '~> 1.9.3'
end
